// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8a-VlLfcvAAGs6AJ55RbpKqqEq5_1iQg',
    appId: '1:975389238544:web:2fe1d845cd455af5403195',
    messagingSenderId: '975389238544',
    projectId: 'ingat-in',
    authDomain: 'ingat-in.firebaseapp.com',
    storageBucket: 'ingat-in.firebasestorage.app',
    measurementId: 'G-7P2L27PK5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDobuu0SCX8U4iHY3Y4SV-5_UmcrkWtqFA',
    appId: '1:975389238544:android:28f0b40b7b34dc69403195',
    messagingSenderId: '975389238544',
    projectId: 'ingat-in',
    storageBucket: 'ingat-in.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA76fU5mfjToS9WRD7WKYYIXiInJ2w6Vcw',
    appId: '1:975389238544:ios:eea8dd161dbc2c01403195',
    messagingSenderId: '975389238544',
    projectId: 'ingat-in',
    storageBucket: 'ingat-in.firebasestorage.app',
    iosBundleId: 'com.example.ingatIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA76fU5mfjToS9WRD7WKYYIXiInJ2w6Vcw',
    appId: '1:975389238544:ios:eea8dd161dbc2c01403195',
    messagingSenderId: '975389238544',
    projectId: 'ingat-in',
    storageBucket: 'ingat-in.firebasestorage.app',
    iosBundleId: 'com.example.ingatIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8a-VlLfcvAAGs6AJ55RbpKqqEq5_1iQg',
    appId: '1:975389238544:web:1d6ab4abe384062f403195',
    messagingSenderId: '975389238544',
    projectId: 'ingat-in',
    authDomain: 'ingat-in.firebaseapp.com',
    storageBucket: 'ingat-in.firebasestorage.app',
    measurementId: 'G-PFG2KHEJFJ',
  );
}
